export const USER_SIGNED_UP = "USER_SIGNED_UP";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const LOADING_MOVIES = "LOADING_MOVIES";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const LOADING_MOVIE = "LOADING_MOVIE";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FAVORITE = "FAVORITE";
export const WATCH_LATER = "WATCH_LATER";
export const FETCH_ACTORS = "FETCH_ACTORS";
export const LOADING_ACTORS = "LOADING_ACTORS";

export const FETCHED_COMMENTS = "FETCHED_COMMENTS";
export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const ADDED_COMMENT = "ADDED_COMMENT";
export const UPDATED_COMMENT = "UPDATED_COMMENT";
export const DELETED_COMMENT = "DELETED_COMMENT";
